//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: input/player/BagInfo.proto
namespace Client.Protobuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BagInfo")]
  public partial class BagInfo : global::ProtoBuf.IExtensible
  {
    public BagInfo() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _description;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"description", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string description
    {
      get { return _description; }
      set { _description = value; }
    }
    private long _max;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"max", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long max
    {
      get { return _max; }
      set { _max = value; }
    }
    private float _vet;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"vet", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float vet
    {
      get { return _vet; }
      set { _vet = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}