//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: input/player/PlayerInfo.proto
// Note: requires additional types generated from: input/player/BagInfo.proto
namespace Client.Protobuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerInfo")]
  public partial class PlayerInfo : global::ProtoBuf.IExtensible
  {
    public PlayerInfo() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private Client.Protobuf.BagInfo _baginfo;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"baginfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Client.Protobuf.BagInfo baginfo
    {
      get { return _baginfo; }
      set { _baginfo = value; }
    }
    private string _opt = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"opt", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string opt
    {
      get { return _opt; }
      set { _opt = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _strlist = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(5, Name=@"strlist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> strlist
    {
      get { return _strlist; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}