//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: input/Enums.proto
namespace Client.ProtoBuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CosDgp")]
  public partial class CosDgp : global::ProtoBuf.IExtensible
  {
    public CosDgp() {}
    
    private CosDgp.Type _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public CosDgp.Type type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _panel;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"panel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int panel
    {
      get { return _panel; }
      set { _panel = value; }
    }
    private int _dgp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"dgp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dgp
    {
      get { return _dgp; }
      set { _dgp = value; }
    }
    private int _user = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"user", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int user
    {
      get { return _user; }
      set { _user = value; }
    }
    private CosDgp.RestartReason _restart_reason = CosDgp.RestartReason.ResetPin;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"restart_reason", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(CosDgp.RestartReason.ResetPin)]
    public CosDgp.RestartReason restart_reason
    {
      get { return _restart_reason; }
      set { _restart_reason = value; }
    }
    private CosDgp.ActiveTask _active_task = CosDgp.ActiveTask.HeartBeat;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"active_task", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(CosDgp.ActiveTask.HeartBeat)]
    public CosDgp.ActiveTask active_task
    {
      get { return _active_task; }
      set { _active_task = value; }
    }
    private int _checkpoint = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"checkpoint", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int checkpoint
    {
      get { return _checkpoint; }
      set { _checkpoint = value; }
    }
    private int _time;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int time
    {
      get { return _time; }
      set { _time = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Type")]
    public enum Type
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Offline", Value=1)]
      Offline = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Online", Value=2)]
      Online = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"RestartReason")]
    public enum RestartReason
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ResetPin", Value=1)]
      ResetPin = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PowerCycle", Value=2)]
      PowerCycle = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ActiveTask")]
    public enum ActiveTask
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"HeartBeat", Value=1)]
      HeartBeat = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Task0", Value=2)]
      Task0 = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}